server:
  port: 80
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_platform?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 123456
  resources:
    static-locations: classpath:/templates  #访问静态页面

  redis:
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 100
        max-wait: -1ms
        max-idle: 8
        min-idle: 1

## spring security配置
  security:
    user:
      name: admin
      password: 123456

JWT:
  signature: $ZJHJWT$